### PR TITLE
Suggestion: to win new translators

### PR DESCRIPTION
**Pull request by kniebremser**
**Advantages:** The language files stay outside of the plugin.  There does not have to be a new version of the plugin to update the language files.
**Disadvantages:** The translations for each language will be unlocked by the Polyglot team, unless there is a PTE (Project Translate Editor).
PTE rights can be applied separately for each language by the plugin developer.
Quite simply, if one translates to 95%, WP will generate a language file that can be downloaded. It is stored outside the plugin. If this file exists, the sparing file in the plugin will no longer be loaded.
**Either way, the plugin developer no longer has 100% control.**

### CODE REVIEW

**Comment by bastianonm** [comment]
I got a couple of issues about code merging, I ported your changes manually to the main branch.
In the next days I'll test plugin and, if everything works, I'll publish to wordpress plugins

**Comment by kniebremser** [comment]
That is very nice. I have no other changes in stock.
I still have ideas but I still do not know how to implement them.

**Comment by kniebremser** [comment]
OK. I have found the error.
Simo56 has reinserted its changes, which causes conflicts in the 3 files.

**Comment by bastianonm** [comment]
Temporanally merged, in the next days I'll import simone's changes

**Comment by kniebremser** [comment]
Thank you and I apologize several times that you now have a lot of work ahead of you. I have removed my changes from Simon for several reasons:

1. The path problems he fixed were due to the fact that he called his website via localhost at his localhost server and did not install a virtual host. This damaged the education for the displayed shortcode. I was shown the complete window path of the gpx file.

2. That every user can upload gpx files is compatible with the WordPress user roles. I also do not understand the meaning, why should a user upload GPX if he can not publish it.
Even if I do not activate the function, and logged in as admin, my files are stored in a folder with username whether I like it or not.
I also found nothing, whether this folder is monitored for read and write permissions.
In the table with the gpx files, also a new column would have to be added, where the admin can see who uploaded which gpx file.

3. I like the idea Copy to Clipboard, but the confirmation button is superfluous.

The insertion of Simon's code can be quite time-consuming, since I've turned over almost every line of code several times.

**Pull request merged**
